name: Priests of Mars
favicon: null
layout_spectrum: 0.7241221689619124
typography_spectrum: 0.08480080706067383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.018660733941942453
  lightness: 0.21505196392536163
  saturation: 0.2144518147688359
  rhythmicContrast: 0.5389638605993241
purpose: []
